name: Minecraft Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Server Configuration
        run: |
          mkdir -p server
          cd server
          echo "eula=true" > eula.txt
          echo "online-mode=false" > server.properties
          
          if [ -d "../mods" ]; then
            mkdir -p mods
            cp -r ../mods/* ./mods/ || true
          fi

      - name: Download Fabric Server 1.21.1
        run: |
          cd server
          curl -JLO "https://meta.fabricmc.net/v2/versions/loader/1.21.1/0.16.0/1.0.1/server/jar"
          mv *.jar server.jar

      - name: Start Ngrok Tunnel and Minecraft
        run: |
          # تحميل وتثبيت Ngrok
          curl -sSL https://bin.equinox.io/c/b4p73zE2hHab/ngrok-v3-stable-linux-amd64.tgz | tar -xz
          
          # إدخال التوكن وتشغيل التانل
          ./ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          ./ngrok tcp 25565 &
          sleep 4
          
          # طباعة الـ IP فـ اللوقس ديريكت
          echo "=================================================="
          echo "SERVER IP & PORT:"
          curl -s http://localhost:4040/api/tunnels | grep -o 'tcp://[^"]*'
          echo "=================================================="
          
          cd server
          java -Xms2G -Xmx6G -jar server.jar nogui
